name: SpotiStats
on: push
jobs:
  build-project:
    name: SpotiStats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build website
        run: npm run build
