name: Build Next.js web application
on: push
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload static webiste
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: build/ 
      - name: Deploy 🚀
        uses: Uraraka-Chan/spotistats
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build